security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        test:
            id: test_user_provider

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            test_auth:
                login_path:  /login
                check_path:  /login_check
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: /secured, roles: ROLE_IS_TEST_AUTHED }

    factories:
        - "%kernel.root_dir%/../src/Test/AuthBundle/Resources/config/auth_factory.yml"